### ISSUE TITLE
black.now.sh failing with CORS error

### ISSUE THREAD

**Issue by chris48s** [jpadilla/black-playground#28]
If I paste any code into https://black.now.sh the right panel does not refresh.

Console logs:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev. (Reason: CORS request did not succeed).

TypeError: NetworkError when attempting to fetch resource.
```

**Comment by hugovk** [comment]
It's working for me now.

**Comment by chris48s** [comment]
Yes this did get resolved at some point but I forgot I had opened an issue about it so I didn't come back and close it. Thanks to whoever fixed it (although I suspect they're not reading this)
