### ISSUE TITLE
Could --fast be either no longer used or configurable?

### ISSUE THREAD

**Issue by ichard26** [jpadilla/black-playground#32]
Hi,

Before I get to the main part of this issue, I just want to say **thank you! 🎉** for making and maintaining the Black playground! Who knows how many new users of Black were introduced through your lovely website. It's also very useful for bug reporters of Black since we ask if the bug they're reporting still exists on master. Same thing for folks like me, Black triagers. It's really handy for when you don't want to or can't setup a local Black environment for testing. Ok, okay, let's get on with the issue:

I have a suggestion to make my life and the lives of other Black bug reporters/contributors. Unfortunately it appears that whatever instance of Black this website is using has been configured to run with `--fast` always. [This example](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACLAFhdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXxXy1j_BK0VXkurN0_QM5EtAsL9v3F7xurQV5mXojEbIWEYe-IZiNzJpDivFk5ncHhXeKZXRv6UG1vi3coSVS2AAAlHKiBZmXUaEAAXSMAQAAAPyhTJ-xxGf7AgAAAAAEWVo=) proves this as the result is showed to the user, while with any local installation of Black using its default of `--safe` would have failed with an AST equivalence error. This is a problem for all bug filers and especially the ones who are filing unstable formatting errors. If the filer is reporting a `ASTs are not equivalent` internal error when they test on master using this website, the error won't show up. This might lead them into incorrectly believing the bug is fixed on master when in reality it isn't. And the unstable formatting errors, they will never show up on this website since `--fast` causes that check to be skipped. Both of these issues are due to `--fast` being used.

And this isn't just in theory, there are real examples where this caused a bit of confusion for everyone. Here's two: https://github.com/psf/black/issues/1194 and https://github.com/psf/black/issues/1588.

I understand that processing power is costly for you, whether you're using a local machine where you pay for energy and do maintenance or a web service that is paid. While I would love to have `--safe` as the default (and I don't care if `--fast` could be accessed or not), I would be also happy with `--safe`/`--fast` being toggleable.

So what do you think? 

Thanks once again, a _Black_ triager.

**Comment by jpadilla** [comment]
@ichard26 hey thank so much for the kind words, really appreciate it. I just deployed this change: 7a81bc1f9c5dff342e01ec52734a1c493f7a004e

The default behavior is now that of `--safe`, but added an option to override.

[Example (--safe)](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACLAFhdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXxXy1j_BK0VXkurN0_QM5EtAsL9v3F7xurQV5mXojEbIWEYe-IZiNzJpDivFk5ncHhXeKZXRv6UG1vi3coSVS2AAAlHKiBZmXUaEAAXSMAQAAAPyhTJ-xxGf7AgAAAAAEWVo=)

[Example (--fast)](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACZAGBdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXxXy1j_BK0VXkurN0_QM5EtAsL9v3F7xurQV5mXojEbIWEYe-IZiNzJpDivFk5ncHhXeKZXRv6UG1vi3ebmkLPTCJHrWG5EimKADBmis-dYpxegABfJoBAAAAs0G_nLHEZ_sCAAAAAARZWg==)

Let me know what you think.

**Comment by ichard26** [comment]
Unfortunately it appears `static/css/style.css` is 404ing 🙁.

![Screenshot (181)](https://user-images.githubusercontent.com/63936253/91925540-36b6de80-eca3-11ea-9320-6b80f132680a.png)

---

![image](https://user-images.githubusercontent.com/63936253/91925012-28b48e00-eca2-11ea-921e-b4e89853afd4.png)
![image](https://user-images.githubusercontent.com/63936253/91925388-e3449080-eca2-11ea-8532-1baa6f50233e.png)

**Comment by jpadilla** [comment]
oops, fixed.

**Comment by ichard26** [comment]
Hey @jpadilla I just played around it and it seems great! I'm particularly impressed that it shows the contents of the log file if present. I'm sure that this will make bug reporting and issue triaging just a bit easier and more friction-less which is always appreciated 😃 

**Thank you so much** for building and deploying this new configuration option!
