### ISSUE TITLE
Python 3.8 syntax not supported

### ISSUE THREAD

**Issue by ignaloidas** [jpadilla/black-playground#33]
E.g. `f"{test=}"` fails with `cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 1)` when black does support it.

**Comment by ichard26** [comment]
Yeah unfortunately the server runnning Black is using CPython 3.6 as [we can tell from this example](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEDALBdAD2IimZxl1N_Wg0-HN9o-La6O_sXBvQ9WEl3RACXLtSbXpDzwyqdfTeA8l6qnrGBJxN5yLNZlI2TG114OovumIsL1envGKHe6sTjZoWxwszxwIhSy9WKr9FUdhu7-qD6Re7tP6V6hjuzBa6PmL_8rwmYA_PpyC8znnbSyx4Et67f9-kKJ-LdCbkuw-cfKAzR6T5KZqsrQsKnK6iUgIZASBI6bZeshDpoCXYTywVxKf4AAAMSLECcFGv9AAHMAYQCAACg1qD5scRn-wIAAAAABFla). You're definitely running Black on CPython 3.8.x (or maybe higher, IDK if Black works on 3.9+) as the parser that supports that feature is only available on that version and higher.

**Comment by jpadilla** [comment]
Will try updating runtime to 3.8

**Comment by jpadilla** [comment]
should be set. d26fbc4
