### ISSUE TITLE
CORS error at https://black.now.sh/

### ISSUE THREAD

**Issue by cyphase** [jpadilla/black-playground#36]
This was reported by someone in #python IRC and I was able to reproduce; just watch the console and type something into the editor on the left of the page to trigger it trying to format.

From the console:

```
XHR OPTIONS https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev CORS Missing Allow Origin
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev. (Reason: CORS request did not succeed).
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. commons.42e0953ff2642a53a4aa.js:6:2214
```

Also the "Report an Issue" link is not working.

**Comment by JonnoFTW** [comment]
Steps to reproduce in chrome (Version 88.0.4324.96) and firefox (84.0.2):

1. Paste code into left panel at https://black.now.sh
2. Loading icon appears in right panel
3. Console logs the following 3 errors and nothing changes in the right panel:

```
Access to fetch at 'https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev' from origin 'https://black.now.sh' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. black.now.sh/:1

index.js:15 POST https://1rctyledh3.execute-api.us-east-1.amazonaws.com/dev net::ERR_FAILED index.js:15 

Uncaught (in promise) TypeError: Failed to fetch commons.42e0953ff2642a53a4aa.js:6 
--

**Comment by jpadilla** [comment]
thanks for the report, working on a fix.

**Comment by jpadilla** [comment]
should be working now https://github.com/jpadilla/black-playground/commit/389276e5312d6e5dc5e55b659bf810a132409c4c

**Comment by cyphase** [comment]
@jpadilla ~~Going to https://black.now.sh/ redirects me to https://black.now.sh/?version=stable&state=undefined, as it did before, but that second link is now giving me a 500 error.~~ Working; I guess that was just an intermediate state.
