### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ichard26** [jpadilla/black-playground#40]
Hi there :wave: 

The master version is getting stuck at https://github.com/psf/black/commit/cac182. This is a problem since people are submitting bug reports under the impression their bug exists on master when in fact it might not (it's actually how I discovered this issue). This is going to get worse with time, especially since we're releasing a hotfix version for 21.4b0 and then updating the stable ref very soon.

I totally understand if you can't keep this functional anymore (it's not like you're getting paid for this anyway!), I'd just like to know whether we should expect this to become functional again.

Regardless, thank you so much for all of your work in keeping this functional over the years! I'm sure it's been a great help to the Black community.

**Comment by jpadilla** [comment]
@ichard26 ahhh sorry about that! I just noticed that travisci disabled the builds. I'll try to unblock now, and move things to GitHub Actions.

**Comment by jpadilla** [comment]
@ichard26 just updated manually, I'll work on moving to GitHub Actions next.

**Comment by ichard26** [comment]
@jpadilla thank you so much!

**Comment by jpadilla** [comment]
should be all set now 😄

**Comment by ichard26** [comment]
Thanks! :black_heart: 

p.s. 
https://github.com/jpadilla/black-playground/blob/37f453dfdac26794d2540fa7e691865927665ba2/.github/workflows/deploy.yml#L44-L51

The step's name should be probably be "Deploy master". Also while ambv/black does redirect to psf/black, it probably would be safer to just reference psf/black directly (you can make that change while fixing the name :) )
