### ISSUE TITLE
Use Python 3.10 in the playground

### ISSUE THREAD

**Issue by isidentical** [jpadilla/black-playground#53]
It seems like the project is still using 3.8, but it is causing some problems when experimenting with new syntax. I wonder whether we can bump it to Python 3.10?

**Comment by jpadilla** [comment]
Can easily bump today to 3.9 since its a supported lambda runtime. 3.10 would require a custom docker image and I most likely wouldnt get to it for a bit.

**Comment by isidentical** [comment]
That works, 3.10 would be also important for the new users of pattern matching but it is not urgent at all. Thanks!

**Comment by jpadilla** [comment]
done in https://github.com/jpadilla/black-playground/commit/97bf2f50439d1568b965bfceef0f2d36a1a92210

**Comment by ilyagr** [comment]
This prevents formatting code with Python 3.10's pattern matching syntax as discussed in https://github.com/psf/black/issues/2242#issuecomment-1372350750.

Is there any change 3.10 is a supported lambda runtime by now?

**Comment by ilyagr** [comment]
I found that checking "Skip temporary sanity checks." makes the playground format Python code with match statements. I'm not sure if that formatting is what it's supposed to be, but it worked well enough for me.
