### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by idek-software** [jpadilla/black-playground#57]
The [website](https://black.vercel.app/?version=main) is down

**To Reproduce**

Open the website

The resulting error is:

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: lhr1::frs25-1645277178676-0769820ef994

**Expected behaviour**

The website opens

**Environment**

Black's version: [main]
OS and Python version: Windows, all Python Versions

**Additional context**

This Serverless Function has crashed.

The connection is working correctly.

Vercel is working correctly.

**Comment by jpadilla** [comment]
thanks for the heads up, fixed.
