### ISSUE TITLE
Provide option for --preview style

### ISSUE THREAD

**Issue by felix-hilden** [jpadilla/black-playground#64]
Hi! Firstly, thanks for the playground, I use it all the time 🙏 Since introducing the [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy) and [`--preview` toggle](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style) in 22.0, we can no longer see the bleeding edge style with playground.

It'd be nice to have a toggle for `--preview` in the options!

**Comment by jpadilla** [comment]
done here https://github.com/jpadilla/black-playground/commit/8406d669b6c35ff58d328e28180e73cb1bb47408 let me know how that works out for you, thanks!

**Comment by felix-hilden** [comment]
Thanks for the quick response, it works! 🎉

**Comment by bersbersbers** [comment]
It's great this option is available. Would be even greater if the text for this option contained the word "preview" so people looking for that one will find it without coming here first to see what to look for :)
