### ISSUE TITLE
Stable fails until preview is toggled off and on

### ISSUE THREAD

**Issue by felix-hilden** [jpadilla/black-playground#65]
Hi! We've encountered a slight issue with the playground, most probably due to #64. This was reported in psf/black#3145.

The playground expects a nonexistent boolean when something is formatted with the stable branch for the first time: [link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABlAEJdAD2IimZxl1N_Wh893mEH4Kqa9Ecnuy7SbFXBFQSKmUwQGyZkVIDGStA7aAcY9ykb-3bFu70HAirbZMdSfL-93G5AAAAAAMzhuztgiWVLAAFeZpwBb6AftvN9AQAAAAAEWVo=). This only happens via a link, so I suspect that the state has something to do with it. Using `version=main` instead does not produce the error. This is also fixed by toggling `preview` on and off again.

**Comment by ParitoshSingh07** [comment]
Seems good to me, the url [Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB7AFddAD2IimZxl1N_Wlws4TBexXdmg613D2W2vO1gykBlg0ElxjidjH2deuosqH32nmM8xj1PdbPxzNWkHiZyYJ80c_DpGmoskeYwGs6I3pBda0cQKIm6K1uk0gAAqicNSjMQmpIAAXN8CaInfR-2830BAAAAAARZWg==) now shows the correct behaviour when i open it up directly!

**Comment by felix-hilden** [comment]
Thanks a bunch again!
